/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardPromptsIndexRouteImport } from './routes/_dashboard/prompts/index'
import { Route as DashboardIssuesIndexRouteImport } from './routes/_dashboard/issues/index'
import { Route as DashboardGoalsIndexRouteImport } from './routes/_dashboard/goals/index'
import { Route as DashboardActivityIndexRouteImport } from './routes/_dashboard/activity/index'
import { Route as DashboardIssuesIssueIdRouteImport } from './routes/_dashboard/issues/$issueId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPromptsIndexRoute = DashboardPromptsIndexRouteImport.update({
  id: '/prompts/',
  path: '/prompts/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/prompts/index.lazy').then((d) => d.Route),
)
const DashboardIssuesIndexRoute = DashboardIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/issues/index.lazy').then((d) => d.Route),
)
const DashboardGoalsIndexRoute = DashboardGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/goals/index.lazy').then((d) => d.Route),
)
const DashboardActivityIndexRoute = DashboardActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/activity/index.lazy').then((d) => d.Route),
)
const DashboardIssuesIssueIdRoute = DashboardIssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/issues/$issueId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/issues/$issueId': typeof DashboardIssuesIssueIdRoute
  '/activity/': typeof DashboardActivityIndexRoute
  '/goals/': typeof DashboardGoalsIndexRoute
  '/issues/': typeof DashboardIssuesIndexRoute
  '/prompts/': typeof DashboardPromptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/issues/$issueId': typeof DashboardIssuesIssueIdRoute
  '/activity': typeof DashboardActivityIndexRoute
  '/goals': typeof DashboardGoalsIndexRoute
  '/issues': typeof DashboardIssuesIndexRoute
  '/prompts': typeof DashboardPromptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/issues/$issueId': typeof DashboardIssuesIssueIdRoute
  '/_dashboard/activity/': typeof DashboardActivityIndexRoute
  '/_dashboard/goals/': typeof DashboardGoalsIndexRoute
  '/_dashboard/issues/': typeof DashboardIssuesIndexRoute
  '/_dashboard/prompts/': typeof DashboardPromptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/issues/$issueId'
    | '/activity/'
    | '/goals/'
    | '/issues/'
    | '/prompts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/issues/$issueId' | '/activity' | '/goals' | '/issues' | '/prompts'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/'
    | '/_dashboard/issues/$issueId'
    | '/_dashboard/activity/'
    | '/_dashboard/goals/'
    | '/_dashboard/issues/'
    | '/_dashboard/prompts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/prompts/': {
      id: '/_dashboard/prompts/'
      path: '/prompts'
      fullPath: '/prompts/'
      preLoaderRoute: typeof DashboardPromptsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/issues/': {
      id: '/_dashboard/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof DashboardIssuesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/goals/': {
      id: '/_dashboard/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof DashboardGoalsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/activity/': {
      id: '/_dashboard/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof DashboardActivityIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/issues/$issueId': {
      id: '/_dashboard/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof DashboardIssuesIssueIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardIssuesIssueIdRoute: typeof DashboardIssuesIssueIdRoute
  DashboardActivityIndexRoute: typeof DashboardActivityIndexRoute
  DashboardGoalsIndexRoute: typeof DashboardGoalsIndexRoute
  DashboardIssuesIndexRoute: typeof DashboardIssuesIndexRoute
  DashboardPromptsIndexRoute: typeof DashboardPromptsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardIssuesIssueIdRoute: DashboardIssuesIssueIdRoute,
  DashboardActivityIndexRoute: DashboardActivityIndexRoute,
  DashboardGoalsIndexRoute: DashboardGoalsIndexRoute,
  DashboardIssuesIndexRoute: DashboardIssuesIndexRoute,
  DashboardPromptsIndexRoute: DashboardPromptsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
